// Mocks generated by Mockito 5.4.6 from annotations
// in task_manager_admin_panel/test/widgets/licenca_wizard_dialog_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:task_manager_admin_panel/models/network_response.dart' as _i2;
import 'package:task_manager_admin_panel/services/network_caller.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNetworkResponse_0 extends _i1.SmartFake
    implements _i2.NetworkResponse {
  _FakeNetworkResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NetworkCaller].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkCaller extends _i1.Mock implements _i3.NetworkCaller {
  MockNetworkCaller() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.NetworkResponse> getRequest(String? url) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRequest,
          [url],
        ),
        returnValue:
            _i4.Future<_i2.NetworkResponse>.value(_FakeNetworkResponse_0(
          this,
          Invocation.method(
            #getRequest,
            [url],
          ),
        )),
      ) as _i4.Future<_i2.NetworkResponse>);

  @override
  _i4.Future<_i2.NetworkResponse> postRequest(
    String? url,
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #postRequest,
          [
            url,
            body,
          ],
        ),
        returnValue:
            _i4.Future<_i2.NetworkResponse>.value(_FakeNetworkResponse_0(
          this,
          Invocation.method(
            #postRequest,
            [
              url,
              body,
            ],
          ),
        )),
      ) as _i4.Future<_i2.NetworkResponse>);

  @override
  _i4.Future<_i2.NetworkResponse> putRequest(
    String? url,
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #putRequest,
          [
            url,
            body,
          ],
        ),
        returnValue:
            _i4.Future<_i2.NetworkResponse>.value(_FakeNetworkResponse_0(
          this,
          Invocation.method(
            #putRequest,
            [
              url,
              body,
            ],
          ),
        )),
      ) as _i4.Future<_i2.NetworkResponse>);

  @override
  _i4.Future<_i2.NetworkResponse> deleteRequest(String? url) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRequest,
          [url],
        ),
        returnValue:
            _i4.Future<_i2.NetworkResponse>.value(_FakeNetworkResponse_0(
          this,
          Invocation.method(
            #deleteRequest,
            [url],
          ),
        )),
      ) as _i4.Future<_i2.NetworkResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
